# mkdocs.yml
# Configuration file for MkDocs (Automated project documentation generator)

# TODO: Change denisecase to your GitHub username (use CTRL F to find all instances)
# TODO: Change applied-ml-template to your repository name (use CTRL F to find all instances)
# TODO: Update site_description
# TODO: Update site_author

site_name: Applied ML Project
site_url: https://14dstcyr.github.io/applied-ml-dstcyr/
repo_url: https://github.com/14dstcyr/applied-ml-dstcyr/
site_description: Professional applied ML project
site_author: Deb St. Cyr
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections # Group navigation items
    - navigation.top # Back-to-top button
    - search.suggest # Search suggestions as you type
    - search.highlight # Highlight search terms
    - content.code.copy # Copy button on code blocks
    - toc.follow # Highlight current section in TOC

  palette:
    - scheme: default # Light/dark mode toggle
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true # Include module names
            show_root_toc_entry: true # Include module in TOC
            docstring_style: google # Professional docstring format
            show_signature_annotations: true
            separate_signature: true    # Makes function signatures easier to read 

markdown_extensions:
  - admonition # Note/Warning/Tip boxes
  - codehilite # Syntax highlighting
  - tables # Markdown tables
  - toc:
      permalink: true # Clickable headers
      toc_depth: 3
  - pymdownx.superfences # Code blocks with syntax highlighting
  - pymdownx.details # Collapsible sections

nav:
  - Home: index.md
  - Classifier Intro (Project 01):
      - Overview: project01/index.md
      - Jupyter Notebook: project01/m101_stcyr.ipynb

  - Classifier Experimentation (Project 02):
      - Overview: project02/index.md
      - Jupyter Notebook: project02/ml02_stcyr.ipynb

  - Classifier Comparison (Project 03):
      - Overview: project03/index.md
      - Jupyter Notebook: project03/m103_stcyr.ipynb

  - Regression Modeling (Project 04):
      - Overview: project04/index.md
      - Jupyter Notebook: project04/m104_stcyr.ipynb

  - Ensemble Models (Project 05):
      - Overview: project05/index.md
      - Jupyter Notebook: project05/ensemble_stcyr.ipynb

  - Final Project (Project 06):
      - Overview: project06/index.md
      - Jupyter Notebook: project06/ml_regression_stcyr.ipynb

  - Banknote Authentication (Midterm Project):
      - Overview: midterm/index.md
      - Jupyter Notebook: midterm/classification_dstcyr.ipynb